import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import postgres from 'postgres';

const sql=postgres(process.env.DATABASE_URL,{ssl:process.env.NODE_ENV==='production'?'require':false});
const secret=process.env.JWT_SECRET;
const json=(res,status,data)=>{res.status(status).json(data)};
const auth=req=>jwt.verify((req.headers.authorization||'').replace('Bearer ',''),secret);
const token=user=>jwt.sign({id:user.id,email:user.email},secret,{expiresIn:'7d'});
const userInfo=user=>({id:user.id,email:user.email,username:user.username});

async function questions(req,res,user){const url=new URL(req.url,'https://dsa.local');const q=url.searchParams.get('q')||'',difficulty=url.searchParams.get('difficulty')||'',topic=url.searchParams.get('topic')||'',status=url.searchParams.get('status')||'';const rows=await sql`SELECT q.*,COALESCE(p.status,'unsolved') status,COALESCE(p.is_starred,false) is_starred,COALESCE(p.notes,'') notes FROM questions q LEFT JOIN user_progress p ON p.question_id=q.id AND p.user_id=${user.id} WHERE (${q}='' OR q.title ILIKE ${'%'+q+'%'} OR q.topics ILIKE ${'%'+q+'%'}) AND (${difficulty}='' OR q.difficulty=${difficulty}) AND (${topic}='' OR q.study_topic=${topic}) AND (${status}='' OR COALESCE(p.status,'unsolved')=${status}) ORDER BY q.study_order`;json(res,200,rows)}
export default async function handler(req,res){try{if(!secret)throw Error('JWT_SECRET is not configured');const path=(req.url||'').split('?')[0].replace(/^\/api\/?/,'');if(path==='health')return json(res,200,{ok:true});if(path==='auth/register'&&req.method==='POST'){const{email,username,password}=req.body||{};if(!email||!password||password.length<4)return json(res,400,{error:'Email and password must be at least 4 characters'});const hash=await bcrypt.hash(password,10);const rows=await sql`INSERT INTO users(email,username,password_hash) VALUES (${email.trim().toLowerCase()},${(username||email.split('@')[0]).trim()},${hash}) RETURNING id,email,username`;return json(res,201,{token:token(rows[0]),user:userInfo(rows[0])})}if(path==='auth/login'&&req.method==='POST'){const rows=await sql`SELECT * FROM users WHERE email=${(req.body?.email||'').trim().toLowerCase()}`;if(!rows[0]||!await bcrypt.compare(req.body?.password||'',rows[0].password_hash))return json(res,401,{error:'Invalid email or password'});return json(res,200,{token:token(rows[0]),user:userInfo(rows[0])})}if(path==='auth/guest'&&req.method==='POST'){let rows=await sql`SELECT * FROM users WHERE email='guest@dsa.local'`;if(!rows[0])rows=await sql`INSERT INTO users(email,username,password_hash) VALUES ('guest@dsa.local','Guest Killer',${await bcrypt.hash('guest-session',10)}) RETURNING *`;return json(res,200,{token:token(rows[0]),user:userInfo(rows[0])})}let user;try{user=auth(req)}catch{return json(res,401,{error:'Authentication required'})}if(path==='auth/me')return json(res,200,(await sql`SELECT id,email,username,created_at FROM users WHERE id=${user.id}`)[0]);if(path==='questions'&&req.method==='GET')return questions(req,res,user);if(path==='questions/meta/topics')return json(res,200,(await sql`SELECT DISTINCT study_topic FROM questions ORDER BY study_topic`).map(x=>x.study_topic));const match=path.match(/^questions\/(\d+)\/progress$/);if(match&&req.method==='PUT'){const{status='unsolved',is_starred=false,notes=''}=req.body||{};if(!['unsolved','in_progress','solved'].includes(status))return json(res,400,{error:'Invalid status'});await sql`INSERT INTO user_progress(user_id,question_id,status,is_starred,notes) VALUES (${user.id},${match[1]},${status},${is_starred},${notes}) ON CONFLICT(user_id,question_id) DO UPDATE SET status=EXCLUDED.status,is_starred=EXCLUDED.is_starred,notes=EXCLUDED.notes,updated_at=NOW()`;return json(res,200,{ok:true})}return json(res,404,{error:'Not found'})}catch(error){console.error(error);json(res,error.code==='23505'?409:500,{error:error.code==='23505'?'That email is already registered':'Server error'})}}
